server:
  port: 8080
  servlet:
    context-path: /demo
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.view: DEBUG
    org.springframework.web.servlet.view.velocity: DEBUG
spring:
  application:
    name: provider
    #MQTT配置信息
  mqtt:
    #MQTT服务地址，端口号默认11883，如果有多个，用逗号隔开
    url: tcp://127.0.0.1:1883
    #用户名
    username: admin
    #密码
    password: gmy900925
    #客户端id(不能重复)
    client:
      id: provider-id
    #MQTT默认的消息推送主题，实际可在调用接口是指定
    default:
      topic: topic
